DROP DATABASE FilmQuiz;
CREATE DATABASE FilmQuiz;
USE FilmQuiz;

CREATE TABLE Person
(
PersonID INT NOT NULL PRIMARY KEY,
PointsPhotoQuiz INT DEFAULT 0,
PointsDescriptionQuiz INT DEFAULT 0,
pq1 INT DEFAULT NULL,
pq2 INT DEFAULT NULL,
pq3 INT DEFAULT NULL,
pq4 INT DEFAULT NULL,
dq1 INT DEFAULT NULL,
dq2 INT DEFAULT NULL,
dq3 INT DEFAULT NULL,
dq4 INT DEFAULT NULL,
fileID varchar(80) DEFAULT NULL
);